#!/usr/bin/env python3

import sys

def factorize_number(number):
    factors = []
    divisor = 2

    while number > 1:
        while number % divisor == 0:
            factors.append(divisor)
            number //= divisor
        divisor += 1

    return factors

def main(filename):
    with open(filename, 'r') as file:
        numbers = [int(line.strip()) for line in file]

    for number in numbers:
        factors = factorize_number(number)
        print(f'{number}={"*".join(map(str, factors))}')

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print('Usage: factors <file>')
        sys.exit(1)

    filename = sys.argv[1]
    main(filename)

