#!/usr/bin/env python3

import sys
import math

def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(math.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

def factorize_number(number):
    for i in range(2, number + 1):
        if number % i == 0 and is_prime(i) and is_prime(number // i):
            return i, number // i

def main(filename):
    with open(filename, 'r') as file:
        numbers = [int(line.strip()) for line in file]

    for number in numbers:
        p, q = factorize_number(number)
        print(f'{number}={p}*{q}')

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print('Usage: factors <file>')
        sys.exit(1)

    filename = sys.argv[1]
    main(filename)

